[package]
name = "ritm"
description = "A package used to experiment with turing machine with k ribbons."
authors = ["Zianne Adrien", "Foucart Axel"]
version = "0.1.0"


[workspace]
resolver = "3"
members = [ "ritm_core" , "ritm_repl"]
